### ISSUE TITLE
I put a backpack INSIDE a backpack and lost all backpacks itens!

### ISSUE THREAD

**Issue by josenaldo** [kwpugh/SimpleBackpack#1]
With the backppack open, in the slot number 9, pressed the 9 key. Then, the selected backpack jumped to the backpack inventory!

I cannot recover the backpack. And, after I close the inventory screen, the backpack disapeared! 

There are some way of retrieve (after a mod update, obvious)?

**Comment by kwpugh** [comment]
Seems that pressing the number of the slot of an open backpack transfer it into the backpack and it cannot be removed.

**Comment by kwpugh** [comment]
Fixed in v1.0.25
