### ISSUE TITLE
Crash on use

### ISSUE THREAD

**Issue by ShadoUrufu** [kwpugh/SimpleBackpack#11]
Can't use the bakcpack, it just crashes when i try using it.

**Comment by kwpugh** [comment]
Crash report log?

**Comment by ShadoUrufu** [comment]
[crash-2021-06-10_23.51.59-client.txt](https://github.com/kwpugh/SimpleBackpack/files/6635486/crash-2021-06-10_23.51.59-client.txt)

**Comment by ShadoUrufu** [comment]
Happens with both the normal and void packs. I'm on the latest update.

**Comment by kwpugh** [comment]
Yeah, that is an older snapshot and will not work on 1.17 with java 16.

**Comment by ShadoUrufu** [comment]
weird, thought i grabbed the latest one. i'll have another look.
