### ISSUE TITLE
there's no backpack slot

### ISSUE THREAD

**Issue by Bakagema00** [kwpugh/SimpleBackpack#12]

**Comment by kwpugh** [comment]
yeah, Minecraft doesn't provide one.  You carry it in your inventory.

**Comment by Bakagema00** [comment]
Even of I downloade trinkets?

**Comment by kwpugh** [comment]
Mods have to code specifically for Trinkets to work with them and I have not decided whether I am going to do that or wait for something better.

**Comment by Bakagema00** [comment]
Gotcha.
