### ISSUE TITLE
Enhancement - "Starter"

### ISSUE THREAD

**Issue by kingstairs** [kwpugh/SimpleBackpack#15]
The main backpack requires iron ingots. How about a lower-level version - 27 slots, using leather + wool instead of iron+wool. Might also want an "upgrade" recipe to convert to the main pack, but that might be risky if there are items in the backpack.

**Comment by kwpugh** [comment]
???????

**Comment by kingstairs** [comment]
(Yeah - mistyped and submitted before I could finish entering the text!)

**Comment by kwpugh** [comment]
all of the other backpack mods do things like that.  I just want to keep it to one, simple, backpack that is the size of a double chest.  If you like/want more of a progression of backpack, you might look at:

https://www.curseforge.com/minecraft/mc-mods/inmis

**Comment by kwpugh** [comment]
Thank you for the suggestion and thank you for playing the mod.
