### ISSUE TITLE
[1.17.1] Bug - Backpack copies the contents of another backpack

### ISSUE THREAD

**Issue by Papuelspapals** [kwpugh/SimpleBackpack#16]
So I was playing some regular mc and using my backpacks and then without me doing anything special or anything really happening my half full backpack B spontaneously copied the complete contents of my full backpack A. I also had an almost full backpack C in my inventory at the time which continued to work normally after this bug happened to me.

All the items were basically duplicated and the items backpack B had before the bug happened are now lost. I have a server backup though, so I can rollback like 20 minutes and maybe fix it. I'm not sure if it will happen again though.

I was using Simple Backpack without any issues for many days before this happened and can't really say why or how this could've happened. The game or mod must have simply made a mistake? I'm completely clueless especially since I didn't change anything about my game, I was just playing and using my backpacks like always.

Maybe naming your backpacks in an anvil could prevent this weird bug? I'm just guessing.

I'm using "SimpleBackpack_Fabric-1.17.1-1.1.13".

Really like your mod btw.

**Comment by kwpugh** [comment]
can you send me the system log of when it happened?   That is odd.  Each backpack, whether named or not, has a unique identifier internally, so I don't think naming them in an anvil would make any difference.

**Comment by Papuelspapals** [comment]
You mean the event log of my server? I can send that later, but it didn't really say anything in the console when it happened, not even gave me en error. Would that still be useful to you?

**Comment by kwpugh** [comment]
yes please.

**Comment by Papuelspapals** [comment]
https://gist.github.com/Papuelspapals/42ee284e89002de676cdfec7f4fca612

This is my server log as a gist thing from the time that bug happened. I edited out paths for privacy but the technical configuration stuff is unchanged of course. I put a note in the log at time [17:08:00] because that's around the time this bug happened to me.

Feel free to close this issue, if you don't think this happens because of your mod. I can't prove this happens because of Simple Backpack anyways and you probably know way more about this than I do. 

If you think it's because of a mod incompatibility could you tell me the mods I should try disabling and if I will have to create a new world if I disable them? I'm ready to disable mods if it could fix my simple backpacks, even though I thought there were no mod incompatibilities because it was working fine for so many days. I'm not expecting an exact answer of course, just your thoughts on this matter.

**Comment by kwpugh** [comment]
Unable to replicate and no other reports,
