### ISSUE TITLE
[1.16.5 & 1.17.1] ShulkerBox can be placed in Backpack, creating infinite storage situation

### ISSUE THREAD

**Issue by AstoriaWinters** [kwpugh/SimpleBackpack#18]
I had this on my servers test server and it was found out that you can put backpacks into shulkers, and then shulkers into backpacks etc. This can create infinite storage pretty much. Is there a way to stop the backpacks from being put in shulkers?

**Comment by kwpugh** [comment]
A will post a fix shortly.

**Comment by kwpugh** [comment]
My solution is to prevent shulker boxes from being placed inside backpacks.  Backpacks can still be placed inside shulker boxes.

**Comment by kwpugh** [comment]
Fixed in latest versions just published for 1.16.5 and 1.17.1
