### ISSUE TITLE
[1.18] Add Hotkey binding possibility to open backpack feature

### ISSUE THREAD

**Issue by lospejos** [kwpugh/SimpleBackpack#20]
Please add "Hotkey binding to open backpack" feature. Thanks

**Comment by kwpugh** [comment]
Not that it hasn't been requested before, still thinking if I want to do that or not.

**Comment by kwpugh** [comment]
Since there are several other backpack mods with advanced features like this and I'm trying to keep it "simple", I will not be moving forward with this at present.
