### ISSUE TITLE
Add ability to put this backpack to Trinkets slots

### ISSUE THREAD

**Issue by lospejos** [kwpugh/SimpleBackpack#22]
Add ability to put this backpack to Trinkets slots.

Trinkets:
https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric

Other backpacks (f.e. https://github.com/Draylar/inmis) already have such ability.

**Comment by kwpugh** [comment]
Great, use those.   I am not at a point to use Trinkets.  I personally do not like the layout of slots.
