### ISSUE TITLE
Bundle not opening

### ISSUE THREAD

**Issue by jaded33** [kwpugh/SimpleBackpack#24]
I assume the bundle opens by placing in your hand and right clicking like the backpack.  However it does not open for me.  Backpack works just fine though.

SimpleBackpack 1.2.24
Minecraft 1.18
Fabric Loader 0.12.11
Fabric API 0.44.0
MacOS M1 MacBook Monterey

I realize there is a newer 1.2.25 version however I have not upgraded to 1.18.1 MC yet (too many mods aren't updated yet).

**Comment by kwpugh** [comment]
Bundles do not open.  They work just like the vanilla Bundle with increased capacity.

https://minecraft.fandom.com/wiki/Bundle

**Comment by jaded33** [comment]
Wow, no wonder why I couldn't get it to work lol!  So sorry for raising the issue here I never used vanilla bundles, but thank you for helping!  I will close this issue.
