### ISSUE TITLE
[1.18.1] Bundle Bug

### ISSUE THREAD

**Issue by MaeunMiri** [kwpugh/SimpleBackpack#25]
We recently updated all our mods to 1.18.1, including Simple Backpack. Now I can't access my bundle or remove an existing one from inside a packpack.

**Comment by kwpugh** [comment]
Bundles cannot be put in backpacks.  You will need  to downgrade to the previous version you had, remove the bundle and then upgrade again.

**Comment by kwpugh** [comment]
This was an issue of players getting caught between version when I changed the bundle nesting in backpack.
