### ISSUE TITLE
[1.18.1] Sorting?

### ISSUE THREAD

**Issue by candyman133** [kwpugh/SimpleBackpack#26]
Have a inventory sorting mod but it does not work on the backpack. Anyway to add a sorting button in the backpack inventory?

**Comment by kwpugh** [comment]
Not sure how difficult that might be, but probably not.  Trying to keep it "simple" so easy to support and update.

**Comment by kwpugh** [comment]
If you want lots of features, might check out Inmis:  https://www.curseforge.com/minecraft/mc-mods/inmis

**Comment by candyman133** [comment]
Coming from Inmis. I actually like the simplicity of this mod so I understand where you're coming from I'll just live without it. Thank you!

**Comment by kwpugh** [comment]
I will not be moving forward with this, I do not want to complicate my code further.
