### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors

### ISSUE THREAD

**Issue by JustFoxx** [kwpugh/SimpleBackpack#27]
Idk why it crashes ._
[crash-2022-01-12_23.19.37-client.txt](https://github.com/kwpugh/SimpleBackpack/files/7858360/crash-2022-01-12_23.19.37-client.txt)
.

**Comment by kwpugh** [comment]
Looks like you do not have the required Cloth Config Mod installed.

**Comment by JustFoxx** [comment]
> Looks like you do not have the required Cloth Config Mod installed.

so could u put on curseforge information that u need Cloth Config ._.

**Comment by kwpugh** [comment]
good point, forgot that.
