### ISSUE TITLE
[1.18.1] One backpack's contents apparently overwrote another

### ISSUE THREAD

**Issue by dranorter** [kwpugh/SimpleBackpack#28]
I don't know what the specific trigger was, but wasn't doing anything funny like renaming the backpacks or storing them in shulkur boxes. Just building and collecting materials for a few hours, with about 10 backpacks in inventory. Eventually I noticed that my "sapling" backpack contained the duplicated contents of my "stone" backpack. The backpack names remain unchanged, so the NBT tags as a whole have not been overwritten, just the "items" portion.

Removing one item stack from the "stone" backpack did not affect the contents of the "sapling" backpack, so they're not tied together, they're just duplicated.

Sorry I don't have any more information on possible causes.

Thanks

**Comment by kwpugh** [comment]
what version are you using? single player or server?

**Comment by dranorter** [comment]
1.18.1, Fabric server on Apex hosting. Here's the mod list. Sorry about the formatting, just copy-pasted it


<html>
<body>


  |   | bclib-1.2.1.jar | JAR File | 887.65 KB | Jan 01 22:26 | Download \| Edit
-- | -- | -- | -- | -- | -- | --
  |   | better-end-1.0.0.jar | JAR File | 87.03 MB | Jan 01 23:17 | Download
  |   | better-nether-6.0.8.jar | JAR File | 21.27 MB | Jan 01 22:35 | Download
  |   | cloth-config-6.1.48-fabric (1).jar | JAR File | 977.34 KB | Jan 01 22:40 | Download \| Edit
  |   | fabric-api-0.45.0+1.18.jar | JAR File | 1.09 MB | Jan 01 22:47 | Download
  |   | fabric-language-kotlin-1.7.1+kotlin.1.6.10.jar | JAR File | 5.77 MB | Jan 01 23:53 | Download
  |   | repurposed_structures_fabric-3.1.13+1.18.1.jar | JAR File | 5.6 MB | Jan 01 22:39 | Download
  |   | SimpleBackpack_Fabric-1.18.1-1.2.27 (1).jar | JAR File | 59.37 KB | Jan 01 22:59 | Download \| Edit
  |   | Terralith_v2.0.7_Fabric+Forge.jar | JAR File | 1.49 MB | Jan 01 22:37 | Download
  |   | vanilla-hammers-3.1.2-1.17.jar | JAR File | 1.28 MB | Dec 12 21:17 | Download
  |   | winged-1.18.1-3.1.0.jar | JAR File | 1.47 MB | Jan 01 23:52 | Download
  |   | wolves-with-armor-1.7.0-1.18.jar


</body>
</html>

**Comment by dranorter** [comment]
I also have the playerdata if that's helpful, but it doesn't look too informative to me.

**Comment by kwpugh** [comment]
please  post the player nbt file

**Comment by dranorter** [comment]
[my player data.zip](https://github.com/kwpugh/SimpleBackpack/files/7858660/my.player.data.zip)

**Comment by kwpugh** [comment]
I  have  no idea  why this  would happen, but then I've never tested/played with that many backpacks with  so  many items.  I  have to wonder  whether  there is an NBT threshold, beyond  which errors start to occur.  I will take  a look.

**Comment by dranorter** [comment]
Just FYI, many of us on the server have been carrying around many backpacks without this issue recurring. So, at this point I've no idea what would reproduce it.

**Comment by kwpugh** [comment]
I'm closing this to another that is active.  https://github.com/kwpugh/SimpleBackpack/issues/36
