### ISSUE TITLE
[1.18.1] Simple Bundle is stuck in Simple Backpack (Tested on 1.2.28 and 1.2.29.jar for Minecraft 1.18.1)

### ISSUE THREAD

**Issue by joeysinclo** [kwpugh/SimpleBackpack#30]
I play on Minecraft 1.18.1 with this mod, and I have an issue where (since at least version 1.2.28.jar) my **Simple Bundle** has been stuck in my **Simple Backpack**.  I used to be able to take **Simple Bundles** in and out of my **Simple Backpack**, and would always do so after a long adventure.  

However after updating to SimpleBackpack 1.2.28 (from 1.2.25.jar I believe), my simple bundle full of items have remained stuck in my backpack since.  Since you've removed all versions prior to SimpleBackpack 1.2.27 from the Curseforge store, downgrading to an older version as an attempt to get the bundle out of the bag isn't an option either.  I can't move the bundle itself, or even right-click to get the items out, because the moment I open my simple backpack, all **Simple Bundles** (inside and outside of the simple backpack) remain "locked", and I'm unable to interact with these simple bundles while my simple backpack is open.  I've also tried updating this to the latest version of SimpleBackpack (version 1.2.29), but it appears the issue hasn't been fixed in the latest version either.

Looking at the Overview for this mod, it appears this is a bug, as the Overview says: 
> Bundles cannot be nested in other Bundles or in the Void Pack.  You can put bundles into Backpacks

![SimpleBackPack_Overview_Underlined](https://user-images.githubusercontent.com/8661736/152654946-151cc58c-02d8-4152-9b58-a16ecda6ede0.png)

**Steps to reproduce**:
Minecraft Version: 1.18.1

1. Get a Simple Backpack and a Simple Bundle (and maybe a couple other random items, if desired)
2. Open your Simple Backpack
3. While the backpack is open, attempt to interact with the simple bundle (i.e. moving the simple bundle, right-clicking to place items in and out of the bundle, etc)

**Expected result**: It should allow you to interact with the **Simple Bundle**, while the **Simple Backpack** is open
**Actual result**: The **Simple Bundle** remains locked while the **Simple Backpack** is open.

I would REALLY appreciate if this bug could be fixed soon.  I've had many valuable items remain stuck in my bag for a pretty long time at this point, and would love to be able to get them out so I can start using them again 🙂 

Thanks!
![2022-02-05_12 38 50](https://user-images.githubusercontent.com/8661736/152654944-1d9b7543-3b4e-4465-a6f5-3b9a1d5babb1.png)
![2022-02-05_12 38 56](https://user-images.githubusercontent.com/8661736/152654945-53954123-caf1-41f7-a8c0-1d60fc58af80.png)

**Comment by kwpugh** [comment]
I restored v25 and v26 on CF, try the previous version you were using while I look at this.

**Comment by kwpugh** [comment]
I had changed the simple bundles so that they cannot be put into backpacks and are locked when a backpack is open.  This is for data integrity reasons and to avoid infinite storage issues.  I will update the CF page accordingly.   You should be able to go back to a previous version and unload the bundle.

**Comment by joeysinclo** [comment]
Ok I see.  I'll give it a shot then and see if it works.  

Thanks for your quick response 👍

**Comment by kwpugh** [comment]
once you get the bundle out of the backpack, you can use the latest version just fine.

**Comment by joeysinclo** [comment]
Cool I was able to successfully get my bag out after downgrading, and was able to upgrade again successfully as well.

Looks like I'm good on my end.  Closing the issue.  Thanks again for the quick response!
