### ISSUE TITLE
Crash Report (Fabric 1.18.1)

### ISSUE THREAD

**Issue by HiddenTides** [kwpugh/SimpleBackpack#33]
Not sure what's going on, the crash report is pretty lengthy and it's hard to read what's causing it to crash the whole game, can't even open with it turned on.  
["https://gist.github.com/HiddenTides/1ceb7348dae552cbddf3b7b2103fd254.js"](https://gist.github.com/HiddenTides/1ceb7348dae552cbddf3b7b2103fd254)

Mods used (Via curseforge) 
Optifine, decorative blocks, decorative winter, simple backpack, twigs.

APIs: Cloth API (fabric), Fabric API

**Comment by kwpugh** [comment]
Looks like you are missing the required Cloth Config API

**Comment by HiddenTides** [comment]
@kwpugh I've been trying to find that and am not really sure where it would be. There's no mention of it anywhere on curseforge or where I can find it.

**Comment by kwpugh** [comment]
https://www.curseforge.com/minecraft/mc-mods/cloth-config

<img width="1322" alt="Screen Shot 2022-03-11 at 12 01 42 PM" src="https://user-images.githubusercontent.com/8809210/157924313-2a889bf2-59c2-41d1-a533-af437bb1a715.png">
