### ISSUE TITLE
NoSuchMethodError: net.minecraft.class_327.method_27528(Lnet/minecraft/class_4587;Lnet/minecraft/class_5348;FFI)I

### ISSUE THREAD

**Issue by bentterp** [kwpugh/SimpleBackpack#4]
I'm getting an error with the last version when I try to open the backpack:

```
java.lang.NoSuchMethodError: net.minecraft.class_327.method_27528(Lnet/minecraft/class_4587;Lnet/minecraft/class_5348;FFI)I
at com.kwpugh.simple_backpack.backpack.BackpackClientScreen.method_2388(BackpackClientScreen.java:46)
```

Full crashlog here: https://paste.ee/p/EOyl8

**Comment by kwpugh** [comment]
You are using: SimpleBackpack_Fabric_1.16.1-1.0.24

Please use latest:  SimpleBackpack_Fabric_1.16.4-1.0.32.jar

**Comment by bentterp** [comment]
Apologies, that was way stupid. I was updating my modlist and somehow missed this one - after having noticed that it existed.......
