### ISSUE TITLE
1.2.36 can't open backpack

### ISSUE THREAD

**Issue by bentterp** [kwpugh/SimpleBackpack#40]
Downgrading to 1.2.35 again restored the functionality.
How can I help troubleshooting, what data to gather? No obvious error messages when trying to open the backpack

**Comment by kwpugh** [comment]
As noted in the changeling, you open the backpack from the offhand now.

![Screen Shot 2022-05-26 at 9 05 26 AM](https://user-images.githubusercontent.com/8809210/170504118-d38c8d00-ac00-4369-8a09-0d1bf35ddf6f.png)
