### ISSUE TITLE
1.19 Fabric (Suggestion) Add Trinket Support

### ISSUE THREAD

**Issue by Tursiops-G** [kwpugh/SimpleBackpack#42]
Would make this the FIRST Fabric 1.19 backpack mod to support wearing in Chestplate/Back slot :)

**Comment by kwpugh** [comment]
This is not something I  want to do.   I think trinkets for a backpack is overkill.

**Comment by Tursiops-G** [comment]
Any plans on making the Backpack Wearable (With Armor)? (1.18.2/1.19+)
