### ISSUE TITLE
Game crashing on start up with mod

### ISSUE THREAD

**Issue by Garaya13** [kwpugh/SimpleBackpack#43]
My game keeps crashing when trying to start up with this mod installed. When I take it out it starts up like normal. Below is the error message I get:

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'simple_backpack'!
Exit Code: -1

**Comment by kwpugh** [comment]
Are you using the required Cloth Config API mod as well?

**Comment by Garaya13** [comment]
I thought I did, but apparently I downloaded the forge version instead. Sorry for the bother, I'm still new to modded minecraft and getting used to the fact that there's 2 mod loaders and thus different files. 
It works perfectly fine now 😄

**Comment by kwpugh** [comment]
Glad it was a simple fix.  enjoy.
