### ISSUE TITLE
[Request] Curios support

### ISSUE THREAD

**Issue by SylisMC** [kwpugh/SimpleBackpack#5]
[Curios](https://www.curseforge.com/minecraft/mc-mods/curios) is an awesome mod that allows the adding additional slots for special items. rings, trinkets, portable crafting tables, backpacks. 

This mod would be really cool to have curio support. being able to equip a bag in a special slot and use a keybind to open it would be amazing, I've created this effect with a data pack but sadly I am unable to add a keybind to interact with the bag. that would require coding within the mod

**Comment by kwpugh** [comment]
It now has Curios support for storing the backpack in the "back" slot.  I will not be adding a keybind.

**Comment by SamhitApple** [comment]
Why no key bind? :(
