### ISSUE TITLE
[Worker-Main-7/ERROR]: Couldn't load item tag c:very_rare_loot

### ISSUE THREAD

**Issue by tserversbfs** [kwpugh/SimpleBackpack#6]
I am getting the following error:

Full error message: [Worker-Main-7/ERROR]: Couldn't load item tag c:very_rare_loot as it is missing following references: gobber2:gobber2_ingot_end (from SimpleBackpack),gobber2:gobber2_ring_teleport (from SimpleBackpack),gobber2:gobber2_ring_ascent (from SimpleBackpack),gobber2:gobber2_ring_swiftness (from SimpleBackpack)

thanks for your help in advance.

Partial log of start:

mc_FABRIC_NewWorld | [init] Starting the Minecraft server...
mc_FABRIC_NewWorld | [04:38:35] [main/INFO]: Loading for game Minecraft 1.16.5
mc_FABRIC_NewWorld | [04:38:35] [main/INFO]: [FabricLoader] Loading 64 mods: fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, gbfabrictools@1.3.2+1.16.4, fabricloader@0.11.1, crowdin-translate@1.2, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.11+9354966b7d, lithium@0.6.3, fabric-dimensions-v1@2.0.6+9354966b7d, fabric-object-builder-api-v1@1.9.4+9354966b7d, java@11, com_squareup_okio_okio@1.16.0, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.1+9354966b7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, com_electronwill_night-config_core@3.6.0, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, playerabilitylib@1.2.1, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, sodium@0.1.0, simple_backpack@1.0.38, fabric-renderer-registries-v1@2.2.1+ca58154a7d, com_github_therandomlabs_trlutils-fabric@1.16-SNAPSHOT, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.30.3+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, minecraft@1.16.5, fabric-screen-handler-api-v1@1.1.5+9354966b7d, resclone@1.2.0, com_github_therandomlabs_trlutils-config@master-SNAPSHOT, modmenu@1.16.7, fabric-command-api-v1@1.0.10+ca58154a7d, phosphor@0.7.1+build.11, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, com_squareup_moshi_moshi@1.9.2, com_electronwill_night-config_toml@3.6.0, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.4+9354966b7d, fabric-rendering-v1@1.5.1+ca58154a7d, fabric-resource-loader-v0@0.4.2+ca58154a7d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, vanilladeathchest@1.16.3-1.11.0.7-fabric, fabric-biome-api-v1@3.1.1+ca58154a7d, modupdater@1.1.11+1.16.2-rc2, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, easierchests@1.16.5-fabric0.30.0-1.6.3, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-models-v0@0.2.1+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d
mc_FABRIC_NewWorld | [04:38:36] [main/WARN]: Mod `com_github_therandomlabs_trlutils-config` (master-SNAPSHOT) does not respect SemVer - comparison support is limited.
mc_FABRIC_NewWorld | [04:38:36] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/data/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
mc_FABRIC_NewWorld | [04:38:38] [main/INFO]: Loaded configuration file for Lithium: 76 options available, 0 override(s) found
mc_FABRIC_NewWorld | [04:38:38] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
mc_FABRIC_NewWorld | [04:38:41] [Thread-66/INFO]: Checking For Mod Updates...
mc_FABRIC_NewWorld | [04:38:42] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
mc_FABRIC_NewWorld | [04:38:43] [Thread-66/INFO]: 0 Mod Updates Found
mc_FABRIC_NewWorld | [04:38:43] [Thread-66/INFO]: Scanned 2 Mods: Fabric API (fabric), ModUpdater (modupdater)
mc_FABRIC_NewWorld | [04:38:43] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
mc_FABRIC_NewWorld | [04:38:43] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
mc_FABRIC_NewWorld | [04:38:43] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
mc_FABRIC_NewWorld | [04:38:43] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
mc_FABRIC_NewWorld | [04:38:43] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
mc_FABRIC_NewWorld | [04:38:43] [main/INFO]: Reloading ResourceManager: Default, bukkit, Brewing_Guide.zip, Fancier+Mansions+v1.0.zip, long-day-e700.zip, AllMobHeads_V5.5+1.16.zip, Fabric Mods (SimpleBackpack, Fabric Tool Attribute API (v1))
rcon_1       | 2021-02-17T04:38:43.731Z RconServer [minecraft:25575]: Connection failed
mc_FABRIC_NewWorld | [04:38:44] [Worker-Main-7/ERROR]: Couldn't load item tag c:very_rare_loot as it is missing following references: gobber2:gobber2_ingot_end (from SimpleBackpack),gobber2:gobber2_ring_teleport (from SimpleBackpack),gobber2:gobber2_ring_ascent (from SimpleBackpack),gobber2:gobber2_ring_swiftness (from SimpleBackpack)
mc_FABRIC_NewWorld | [04:38:44] [Worker-Main-7/INFO]: Loaded 7 recipes
mc_FABRIC_NewWorld | [04:38:45] [Worker-Main-7/INFO]: Loaded 1430 advancements
mc_FABRIC_NewWorld | [04:38:45] [main/INFO]: BeforeConstant is searching for constants in method with descriptor (Lnet/minecraft/class_1297;)V
mc_FABRIC_NewWorld | [04:38:45] [main/INFO]:   BeforeConstant found CLASS constant: value = Lnet/minecraft/class_1309;, typeValue = Lnet/minecraft/class_1309;
mc_FABRIC_NewWorld | [04:38:45] [main/INFO]:     BeforeConstant found a matching constant value at ordinal 0
mc_FABRIC_NewWorld | [04:38:45] [main/INFO]:   BeforeConstant found CLASS constant: value = Lnet/minecraft/class_1309;, typeValue = Lnet/minecraft/class_1309;
mc_FABRIC_NewWorld | [04:38:45] [main/INFO]:     BeforeConstant found a matching constant value at ordinal 1
mc_FABRIC_NewWorld | [04:38:45] [main/INFO]:   BeforeConstant found CLASS constant: value = Lnet/minecraft/class_1309;, typeValue = Lnet/minecraft/class_1309;
mc_FABRIC_NewWorld | [04:38:45] [main/INFO]:     BeforeConstant found a matching constant value at ordinal 2
mc_FABRIC_NewWorld | [04:38:45] [main/INFO]:       BeforeConstant found TypeInsn       [INSTANCEOF]
mc_FABRIC_NewWorld | [04:38:45] [main/INFO]:   BeforeConstant found CLASS constant: value = Lnet/minecraft/class_1309;, typeValue = Lnet/minecraft/class_1309;
mc_FABRIC_NewWorld | [04:38:45] [main/INFO]:     BeforeConstant found a matching constant value at ordinal 3
mc_FABRIC_NewWorld | [04:38:45] [main/INFO]: Applied 0 biome modifications to 0 of 79 new biomes in 11.92 ms
mc_FABRIC_NewWorld | [04:38:46] [Server thread/INFO]: Starting minecraft server version 1.16.5
mc_FABRIC_NewWorld | [04:38:46] [Server thread/INFO]: Loading properties
mc_FABRIC_NewWorld | [04:38:46] [Server thread/INFO]: Default game type: SURVIVAL
mc_FABRIC_NewWorld | [04:38:46] [Server thread/INFO]: Generating keypair
mc_FABRIC_NewWorld | [04:38:46] [Server thread/INFO]: Starting Minecraft server on *:25565
mc_FABRIC_NewWorld | [04:38:46] [Server thread/INFO]: Using epoll channel type
mc_FABRIC_NewWorld | [04:38:46] [Server thread/INFO]: Preparing level "world"
mc_FABRIC_NewWorld | [04:38:46] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
mc_FABRIC_NewWorld | [04:38:48] [Server thread/INFO]: Preparing spawn area: 0%
mc_FABRIC_NewWorld | [04:38:48] [Server thread/INFO]: Preparing spawn area: 0%
mc_FABRIC_NewWorld | [04:38:48] [Server thread/INFO]: Preparing spawn area: 0%
mc_FABRIC_NewWorld | [04:38:48] [Worker-Main-10/INFO]: Preparing spawn area: 0%
mc_FABRIC_NewWorld | [04:38:48] [Worker-Main-9/INFO]: Preparing spawn area: 85%
mc_FABRIC_NewWorld | [04:38:49] [Server thread/INFO]: Time elapsed: 2454 ms
mc_FABRIC_NewWorld | [04:38:49] [Server thread/INFO]: Done (2.945s)! For help, type "help"
mc_FABRIC_NewWorld | [04:38:49] [Server thread/INFO]: Starting remote control listener
mc_FABRIC_NewWorld | [04:38:49] [Server thread/INFO]: Thread RCON Listener started
mc_FABRIC_NewWorld | [04:38:49] [Server thread/INFO]: RCON running on 0.0.0.0:25575
mc_FABRIC_NewWorld | [04:38:53] [RCON Listener #1/INFO]: Thread RCON Client /172.28.0.2 started

**Comment by kwpugh** [comment]
fixed in next update
