### ISSUE TITLE
[1.17] Trinkets Support

### ISSUE THREAD

**Issue by IdrisQe** [kwpugh/SimpleBackpack#7]
I know this is sort of already covered by the Curios support, but it would be nice to have support for Trinkets as well. The modpack I'm running currently has Trinkets for a few things, but has nothing that requires Curios so I don't want to install Curios solely for this, but it would also be nice to not need to take up my chest slot.

Definitely not a high priority or anything, especially since Trinkets is much less ubiquitous than Curios especially in 1.16.

Edit: Oh, you can't actually put it in the Vanilla chest slot, and it can be opened from the inventory... And you can have any number of them. Heck.

**Comment by kwpugh** [comment]
I won't be adding Trinkets in 1.16, but will be moving to it in 1.17 since Curios is sunsetting/merging in with Trinkets in 1.17.

Stay tuned.

**Comment by kwpugh** [comment]
This is a broader topic for all of my mods, so do not need a specific issue for it.
