### ISSUE TITLE
Crash report (Fabric 1.16.5)

### ISSUE THREAD

**Issue by PlushCola** [kwpugh/SimpleBackpack#8]
https://gist.githubusercontent.com/natanfudge/4edd049bc4d4a1ac349f9cc234726e37/raw/3792a51265149fe58a3fb57608a3ccbd7f8f7d6b/crash.txt

I am new to reporting crashes like this. sorry if i shouldn't put it here.

All i did was put the mod in the folder with the API and everything than try to start it, it got past the mojang load screen than it said it couldn't load due to this mod, is there anything i can do to fix this? it works just fine without it but i'd like to have backpacks.

Thanks for taking time out of your day to read this!

**Comment by PlushCola** [comment]
I realized i may not have had the right API, sorry about this lol

**Comment by PlushCola** [comment]
Nope, turns out i'm still having the issue but it's this now:

https://gist.githubusercontent.com/natanfudge/90355f7388ef3a6508ca41219337c31e/raw/8e3a7b4514ee11f8de5414f97c4b65d8c51c70cd/crash.txt

**Comment by kwpugh** [comment]
Looks like a conflict with Not Enough Crates.  I will have to take a look.

**Comment by PlushCola** [comment]
OH! thanks! i'll look.

**Comment by PlushCola** [comment]
oh wait

**Comment by PlushCola** [comment]
i'm silly and didn't read the response right lol.

**Comment by PlushCola** [comment]
Right, After some Moving in and out of the mod folder suddenly it works! i have no clue why however but...at least it works?
