### ISSUE TITLE
[1.16.5] Backpack dupe glitch

### ISSUE THREAD

**Issue by FarukonTV** [kwpugh/SimpleBackpack#9]
I hosted a multiplayer server for all of my friends to play, and we installed this mod as one amongst many to have. We found out, however, that opening the backpack as you throw it out of your inventory will allow you to take items out of the backpack, and when you pick the backpack up again, the item you took will be in both your inventory as well as in the backpack.

**Comment by kwpugh** [comment]
This no longer exists in 1.17
